name: BlueMapSignMarkers
version: ${version}
main: dev.kugge.signmarkers.SignMarkers
api-version: 1.19
authors: [kugge]
depend: [BlueMap]
description: Add markers to BlueMap with signs

commands:
  signmarkers:
    description: SignMarkers commands
    usage: /signmarkers <command>
    permission: signmarkers.command